name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: pip install pillow && python crop_wallpaper.py
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            weather.png
            youtube.png
            reddit.png
            music.png
            date.png
            gmail.png
            spotify.png
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
